version: '3.8'
services:
  server_svc:
    container_name: server_host
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "48000:8000"
    environment:
      DEEPRISK_MONGO_HOST: mongo_host
      DEEPRISK_MONGO_USER: admin
      DEEPRISK_MONGO_PASS: admin
      DEEPRISK_DTAPI_HOST: ${ENV_DEEPRISK_DTAPI_HOST}
      DEEPRISK_DTAPI_TOKEN: ${ENV_DEEPRISK_DTAPI_TOKEN}
    depends_on:
      - mongo_svc
  mongo_svc:
    image: mongo:latest
    container_name: mongo_host
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "./data/db/mongo:/data/db"
  mongo_view_svc:
    image: mongo-express:latest
    container_name: mongo_view_host
    ports:
      - 48081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo_host
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo_host:27017
    volumes:
      - "./data/db/mongo:/data/db"
    depends_on:
      - mongo_svc
